<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-10-05 17:27
=======
# Generated by Django 3.2.6 on 2021-09-28 13:11
>>>>>>> 9c69cd86133c3c8e2c77bf96ee1beb943557f444

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
